namespace EtabSharp.Loads.LoadCases.Models;

/// <summary>
/// Summary information about load cases in the model.
/// </summary>
public class LoadCaseSummary
{
    /// <summary>
    /// Total number of load cases.
    /// </summary>
    public int TotalCases { get; set; }

    /// <summary>
    /// Number of linear static cases.
    /// </summary>
    public int LinearStaticCases { get; set; }

    /// <summary>
    /// Number of nonlinear static cases.
    /// </summary>
    public int NonlinearStaticCases { get; set; }

    /// <summary>
    /// Number of modal cases.
    /// </summary>
    public int ModalCases { get; set; }

    /// <summary>
    /// Number of response spectrum cases.
    /// </summary>
    public int ResponseSpectrumCases { get; set; }

    /// <summary>
    /// Number of linear history cases.
    /// </summary>
    public int LinearHistoryCases { get; set; }

    /// <summary>
    /// Number of nonlinear history cases.
    /// </summary>
    public int NonlinearHistoryCases { get; set; }

    /// <summary>
    /// Number of buckling cases.
    /// </summary>
    public int BucklingCases { get; set; }

    /// <summary>
    /// Number of moving load cases.
    /// </summary>
    public int MovingLoadCases { get; set; }

    /// <summary>
    /// Number of auto-generated cases.
    /// </summary>
    public int AutoGeneratedCases { get; set; }

    /// <summary>
    /// Other case types.
    /// </summary>
    public int OtherCases { get; set; }

    public override string ToString()
    {
        return $"Load Cases Summary: Total={TotalCases}, Linear={LinearStaticCases}, " +
               $"Nonlinear={NonlinearStaticCases}, Modal={ModalCases}, " +
               $"ResponseSpectrum={ResponseSpectrumCases}, History={LinearHistoryCases + NonlinearHistoryCases}, " +
               $"Buckling={BucklingCases}, Auto={AutoGeneratedCases}";
    }
}